name: app_healthcare
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  fl_chart: ^0.65.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.14.0
  google_fonts: ^6.1.0

  firebase_auth_web: ^5.9.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Charts - THÊM MỚI
  # fl_chart: ^0.66.0

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
