name: app_healthcare
description: "A Flutter healthcare tracking application with Firebase integration."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_auth_web: ^5.9.0
  
  firebase_storage: ^11.5.0
  cloud_firestore: ^4.17.0

  # UI & Fonts
  google_fonts: ^6.1.0
  
  # Charts
  fl_chart: ^0.65.0
  
  http: ^1.2.1
  url_launcher: ^6.1.12
  
  # Image Picker (Avatar Upload)
  image_picker: ^1.1.2
  
  # Additional utilities
  cupertino_icons: ^1.0.6
  intl: ^0.18.1

  # Pedometer
  pedometer: ^4.0.1
  
  # Local Notifications - THÊM MỚI
  flutter_local_notifications: ^17.0.0
  
  timezone: ^0.9.2
  path: ^1.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/