// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL9dP4DhY3ISjFmEl-_EKo3Je1ldKwlTo',
    appId: '1:377997945929:web:4733224178bae4c7b5e398',
    messagingSenderId: '377997945929',
    projectId: 'healthapp-d2c4b',
    authDomain: 'healthapp-d2c4b.firebaseapp.com',
    storageBucket: 'healthapp-d2c4b.firebasestorage.app',
    measurementId: 'G-8VB9SCX2VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmKh-zFp6Iek4MJHEampJYNeZsyzkldh8',
    appId: '1:377997945929:android:b2610ac3c91e07bab5e398',
    messagingSenderId: '377997945929',
    projectId: 'healthapp-d2c4b',
    storageBucket: 'healthapp-d2c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEtbMlFtEsjEvj0vmlZTS8QZG0p6_hFLk',
    appId: '1:377997945929:ios:0e2d33b979dd8f42b5e398',
    messagingSenderId: '377997945929',
    projectId: 'healthapp-d2c4b',
    storageBucket: 'healthapp-d2c4b.firebasestorage.app',
    iosClientId: '377997945929-qha25c1p901ku9pcjor5384cgsh7nj1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.appHealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEtbMlFtEsjEvj0vmlZTS8QZG0p6_hFLk',
    appId: '1:377997945929:ios:0e2d33b979dd8f42b5e398',
    messagingSenderId: '377997945929',
    projectId: 'healthapp-d2c4b',
    storageBucket: 'healthapp-d2c4b.firebasestorage.app',
    iosClientId: '377997945929-qha25c1p901ku9pcjor5384cgsh7nj1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.appHealthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL9dP4DhY3ISjFmEl-_EKo3Je1ldKwlTo',
    appId: '1:377997945929:web:d66fb0715310be61b5e398',
    messagingSenderId: '377997945929',
    projectId: 'healthapp-d2c4b',
    authDomain: 'healthapp-d2c4b.firebaseapp.com',
    storageBucket: 'healthapp-d2c4b.firebasestorage.app',
    measurementId: 'G-DEMMH16DN9',
  );
}
